// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlmacw0-TejTGKgXdrWYqcdRADynHzpA',
    appId: '1:788367055164:android:61acf9b4a78626ca4ba639',
    messagingSenderId: '788367055164',
    projectId: 'push-me-6fc5d',
    storageBucket: 'push-me-6fc5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXQbdSZx9bVPq0Kf5UuRcxFNSUVlWlAU',
    appId: '1:788367055164:ios:475ecbe417d604734ba639',
    messagingSenderId: '788367055164',
    projectId: 'push-me-6fc5d',
    storageBucket: 'push-me-6fc5d.appspot.com',
    androidClientId: '788367055164-n107d6fut0pvl0trrb6sb7ccnqcistv3.apps.googleusercontent.com',
    iosClientId: '788367055164-jcot9h90tm2gq56e2jsiqr0fuphj2crj.apps.googleusercontent.com',
    iosBundleId: 'com.edentech.etJob',
  );
}
